// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuvhrLaLNtYnmmanNufrb3idrOx7aaIJs',
    appId: '1:394416079011:web:9b0cc9fc5b018955b2ff16',
    messagingSenderId: '394416079011',
    projectId: 'moodmate-8438a',
    authDomain: 'moodmate-8438a.firebaseapp.com',
    storageBucket: 'moodmate-8438a.firebasestorage.app',
    measurementId: 'G-FJDZ9X0TWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaadNbohC3nWsL7XU7jhAwThiEEEUbwMc',
    appId: '1:394416079011:android:b9000d33f909e85db2ff16',
    messagingSenderId: '394416079011',
    projectId: 'moodmate-8438a',
    storageBucket: 'moodmate-8438a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADCZL_6KwaYL5HedIu8dwTjjN5fAL2eIc',
    appId: '1:394416079011:ios:83811cf7eef012f2b2ff16',
    messagingSenderId: '394416079011',
    projectId: 'moodmate-8438a',
    storageBucket: 'moodmate-8438a.firebasestorage.app',
    iosBundleId: 'com.example.finalwalaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADCZL_6KwaYL5HedIu8dwTjjN5fAL2eIc',
    appId: '1:394416079011:ios:83811cf7eef012f2b2ff16',
    messagingSenderId: '394416079011',
    projectId: 'moodmate-8438a',
    storageBucket: 'moodmate-8438a.firebasestorage.app',
    iosBundleId: 'com.example.finalwalaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuvhrLaLNtYnmmanNufrb3idrOx7aaIJs',
    appId: '1:394416079011:web:f0ab6d2b8fb6dddcb2ff16',
    messagingSenderId: '394416079011',
    projectId: 'moodmate-8438a',
    authDomain: 'moodmate-8438a.firebaseapp.com',
    storageBucket: 'moodmate-8438a.firebasestorage.app',
    measurementId: 'G-B55XJQZCQQ',
  );

}